### ISSUE TITLE
Random Contact Blackbird Checklist

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/random-contact#16]
- [x] Verify string translations if applicable
- [x] Update Version Name and Code in build.gradle
- [x] Update Version details in strings.xml
- [x] Add Change history to VersionHistory.md
- [x] Generate Release Build
- [x] Prepare Release notes and promotional content
- [x] Create Beta Release in Google Play Console
- [x] Upload apk and verify details
- [x] Upload Deobfuscation file if applicable 
- [x] Publish to Beta
- [x] Merge changes to master
- [x] Complete the Milestone and Tag as release
