### ISSUE TITLE
RandomContact Telephone Release Checklist

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/random-contact#9]
- [x] Verify string translations if applicable
- [x] Update Version Name and Code in build.gradle
- [x] Update Version details in strings.xml
- [x] Generate Release Build
- [x] Prepare Release notes and promotional content
- [ ] Create Beta Release in Google Play Console
- [x] Add Change history to VersionHistory.md
- [ ] Merge changes to master
- [ ] Upload apk and verify details
- [ ] Upload Deobfuscation file if applicable - [ ] Publish to Beta
- [ ] Complete the Milestone and Tag as release
